name: Build and Publish Container Image

on:
  push:
    tags: [v*.*.*]

jobs:
  build-container-image:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2

    - name: Get version
      run: echo "IMAGE_TAG=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV


    - name: Build Docker Image
      run: docker build -t ghcr.io/${GITHUB_REPOSITORY}:${IMAGE_TAG} .
    
    - name: Login
      run: docker login -u publisher -p ${GHCR_TOKEN} ghcr.io
      env:
        GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}

    - name: Push
      run: docker push ghcr.io/${GITHUB_REPOSITORY}:${IMAGE_TAG}

  build-binary-amd64:
    name: Release Go Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin, openbsd]
        goarch: [amd64]
    steps:

    - uses: actions/checkout@v2

    - uses: wangyoucao577/go-release-action@v1.14
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
        goversion: "https://dl.google.com/go/go1.16.linux-amd64.tar.gz"
        project_path: "./"
        binary_name: "discord-stock-tickerboard"
        md5sum: FALSE
        
  build-binary-arm:
    name: Release Go Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux]
        goarch: [arm64, arm]
    steps:

    - uses: actions/checkout@v2

    - uses: wangyoucao577/go-release-action@v1.14
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
        goversion: "https://dl.google.com/go/go1.16.linux-amd64.tar.gz"
        project_path: "./"
        binary_name: "discord-stock-tickerboard"
        md5sum: FALSE
